// Free isolated rehearsal. Stores no production notification credentials or Auth tokens.
import http from 'node:http';import fs from 'node:fs/promises';import webpush from 'web-push';import {database} from './database.mjs';import {createHandler,Failure,PILOT} from '../../supabase/functions/sales-notifications/core.mjs';import {createRoutingStore} from '../../supabase/functions/sales-notifications/routing-store.mjs';
const root=new URL('./',import.meta.url);const {db,transaction,query}=await database(new URL('./private-data',root).pathname);const keyPath=new URL('./private-vapid.json',root);let keys;try{keys=JSON.parse(await fs.readFile(keyPath,'utf8'))}catch{keys=webpush.generateVAPIDKeys();await fs.writeFile(keyPath,JSON.stringify(keys),{mode:0o600})}
const source=await fs.readFile(new URL('../../supabase/functions/sales-notifications/index.ts',root),'utf8');const key=source.match(/const SALES_KEY="([^"]+)"/)[1];const SALES='https://ejhwbovqtcujjwvjniyt.supabase.co';
async function sales(token,path){const r=await fetch(SALES+path,{headers:{apikey:key,Authorization:'Bearer '+token},signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Failure(path.startsWith('/auth')?'invalid_sales_jwt':'sales_read_unavailable',path.startsWith('/auth')?401:503);return r.json()}
const dependencies={verify:t=>sales(t,'/auth/v1/user'),admin:async t=>{const r=await fetch(SALES+'/rest/v1/rpc/is_admin',{method:'POST',headers:{apikey:key,Authorization:'Bearer '+t,'Content-Type':'application/json'},body:'{}',signal:AbortSignal.timeout(10000)});return r.ok&&(await r.json())===true},identity:async(t,id)=>{const links=await sales(t,'/rest/v1/agent_user_links?select=user_id,agent_id,active&active=eq.true&user_id=eq.'+encodeURIComponent(id));if(links.length!==1)return null;const agents=await sales(t,'/rest/v1/agents?select=id,name,active&id=eq.'+encodeURIComponent(links[0].agent_id));return agents.length===1?{user:id,agent:agents[0].id,name:agents[0].name,active:links[0].active,agentActive:agents[0].active}:null},latestSubmission:async t=>(await sales(t,'/rest/v1/sales_submissions?select=id,agent_id,submitter_user_id,status,revision&status=eq.approved&order=updated_at.desc&limit=1'))[0],submission:async(t,id)=>(await sales(t,'/rest/v1/sales_submissions?select=id,agent_id,submitter_user_id,status,revision&id=eq.'+encodeURIComponent(id)))[0],audits:(t,id)=>sales(t,'/rest/v1/sales_submission_reviews?select=action,revision,acted_at&submission_id=eq.'+encodeURIComponent(id))};
let snapshot=0;async function audit(action,result){const rows=await query('select event_type,revision,recipient_role,status,created_at,sent_at,error_code from sales_notification_deliveries order by created_at');await fs.writeFile(new URL('./private-audit.json',root),JSON.stringify({action,result,deliveries:rows.rows},null,2));snapshot++}
http.createServer(async(req,res)=>{try{const origins=JSON.parse(await fs.readFile(new URL('./origins.json',root),'utf8'));const origin=req.headers.origin;if(!origin||!origins.includes(origin)){res.writeHead(403);return res.end('Origin not allowed')}
 const pieces=[];let size=0;for await(const part of req){size+=part.length;if(size>4096){res.writeHead(413);return res.end()}pieces.push(part)}const body=Buffer.concat(pieces).toString();const trackerOrigin=origins.find(x=>x.startsWith('https://'))||origin;
 const routing=createRoutingStore({transaction,query,trackerOrigin,agentOrigin:'https://ngc-super-app.vercel.app',settings:async()=>({vapid_public_key:keys.publicKey,vapid_private_key:keys.privateKey}),send:async(subscription,payload)=>{if(payload.notification.title!=='TEST · Tracker notifications')throw new Failure('isolated_real_business_push_disabled',403);webpush.setVapidDetails('mailto:desmondchong@nextgen-c.com',keys.publicKey,keys.privateKey);await webpush.sendNotification(subscription,JSON.stringify(payload),{TTL:300,urgency:'normal',timeout:10000})}});
 const response=await createHandler({...dependencies,...routing,origins})(new Request('http://127.0.0.1:4211/',{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body}: {})}));const text=await response.text();res.writeHead(response.status,Object.fromEntries(response.headers));res.end(text);if(req.method==='POST'){let action;try{action=JSON.parse(body).action}catch{action='invalid'}if(response.ok&&['adminDryRun','adminRoutingDryRun','adminTest'].includes(action))await audit(action,JSON.parse(text));}
 }catch{res.writeHead(503,{'Content-Type':'application/json'});res.end('{"error":"isolated_notification_unavailable"}')}}).listen(4211,'127.0.0.1',()=>console.log('Isolated Phase 7B backend ready on 127.0.0.1:4211; production writes and business pushes disabled'));
