export const PILOT={user:'c989765f-709c-4edb-98ce-1c669ce8c0de',agent:'0ae042fb-3c77-4c2d-a771-54b0b32e6d2a',name:'Chong Chian Aik'};
export const CONTENT={submitted:['New sales submission','A sales submission is ready for review.'],resubmitted:['Sales resubmitted','A revised sales submission is ready for review.'],changes_requested:['Changes requested','Your sales submission needs an update.'],approved:['Sales approved','Your sales submission has been approved.'],rejected:['Sales rejected','Your sales submission was not approved.'],test:['TEST · Sales notification','Sales notifications are working on this device.']};
export class Failure extends Error{constructor(code,status=400){super(code);this.code=code;this.status=status;}}
export function pilot(identity){if(!identity||identity.user!==PILOT.user||identity.agent!==PILOT.agent||identity.name!==PILOT.name||!identity.active||!identity.agentActive)throw new Failure('pilot_not_enabled',403);return identity;}
export function endpoint(value){if(typeof value!=='string'||value.length>2048)throw new Failure('invalid_endpoint');try{if(new URL(value).protocol!=='https:')throw 0}catch{throw new Failure('invalid_endpoint')}return value;}
export function eligible(event,s,audits,user,admin){if(!['submitted','resubmitted','changes_requested','approved','rejected'].includes(event))throw new Failure('invalid_event');if(!s||s.agent_id!==PILOT.agent||s.submitter_user_id!==PILOT.user)throw new Failure('pilot_not_enabled',403);if(['submitted','resubmitted'].includes(event)){if(user!==s.submitter_user_id)throw new Failure('not_owner',403)}else if(!admin)throw new Failure('admin_required',403);const status=['submitted','resubmitted'].includes(event)?'pending':event;const a=audits.filter(x=>x.action===event&&x.revision===s.revision).sort((a,b)=>Date.parse(b.acted_at)-Date.parse(a.acted_at))[0];if(!a||s.status!==status)throw new Failure('event_state_mismatch',409);return{revision:s.revision,actedAt:a.acted_at};}
export function createHandler(d){return async req=>{const origin=req.headers.get('origin'),headers={'Content-Type':'application/json','Cache-Control':'no-store','Vary':'Origin','Access-Control-Allow-Headers':'authorization,content-type,apikey','Access-Control-Allow-Methods':'POST,OPTIONS',...(d.origins.includes(origin)?{'Access-Control-Allow-Origin':origin}:{})};const json=(x,status=200)=>new Response(JSON.stringify(x),{status,headers});if(req.method==='OPTIONS')return new Response(null,{status:204,headers});try{if(origin&&!d.origins.includes(origin))throw new Failure('origin_not_allowed',403);if(req.method!=='POST')throw new Failure('method_not_allowed',405);const raw=await req.text();if(raw.length>4096)throw new Failure('request_too_large',413);const body=JSON.parse(raw);if(!body||Array.isArray(body))throw new Failure('invalid_request');const allowed={status:['action','endpoint'],bind:['action','endpoint'],disable:['action','endpoint'],dryRun:['action','endpoint','submission_id','event_type'],test:['action','endpoint'],event:['action','submission_id','event_type']};if(!allowed[body.action]||Object.keys(body).some(k=>!allowed[body.action].includes(k)))throw new Failure('invalid_request');const token=req.headers.get('authorization')?.match(/^Bearer (.+)$/)?.[1];if(!token)throw new Failure('invalid_sales_jwt',401);const user=await d.verify(token);if(!user?.id)throw new Failure('invalid_sales_jwt',401);
if(['status','bind','disable','test'].includes(body.action)||body.action==='dryRun'&&!body.submission_id){pilot(await d.identity(token,user.id));const e=endpoint(body.endpoint);if(body.action==='bind')return json(await d.bind(e));if(body.action==='disable')return json(await d.disable(e));if(body.action==='status')return json(await d.status(e));if(body.action==='dryRun')return json(await d.dryRun(e));return json(await d.deliver({event:'test',endpoint:e,submission:null,revision:0,actedAt:null,dryRequired:true}));}
if(!/^[0-9a-f-]{36}$/i.test(body.submission_id||''))throw new Failure('invalid_submission');const s=await d.submission(token,body.submission_id);const admin=await d.admin(token);const a=eligible(body.event_type,s,await d.audits(token,s?.id),user.id,admin);pilot(await d.identity(token,s.submitter_user_id));if(body.action==='dryRun')return json(await d.dryRun(null,{...a,event:body.event_type,submission:s.id}));return json(await d.deliver({...a,event:body.event_type,submission:s.id,endpoint:null,dryRequired:false}));
}catch(e){const code=e instanceof Failure?e.code:e instanceof SyntaxError?'invalid_json':'notification_unavailable';d.log?.(code);return json({error:code},e instanceof Failure?e.status:503)}};}
