import {Pool} from 'npm:pg@8.16.3';
import webpush from 'npm:web-push@3.6.7';
import {createHandler,Failure,PILOT,CONTENT} from './core.mjs';
const SALES='https://ejhwbovqtcujjwvjniyt.supabase.co';
const SALES_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqaHdib3ZxdGN1amp3dmpuaXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1MDYyMjksImV4cCI6MjA4MTA4MjIyOX0.GBf7fuVOE9m3jCcPGSaMWrfWyaRG6Bo3p5kb8wE6ZFo";
const pool=new Pool({connectionString:Deno.env.get('SUPABASE_DB_URL'),max:3,connectionTimeoutMillis:10000,idleTimeoutMillis:30000});
const origins=['https://ngc-super-app.vercel.app','https://ngc-sales-tracker.vercel.app'];
async function sales(token:string,path:string,options:Record<string,unknown>={}){const r=await fetch(SALES+path,{headers:{apikey:SALES_KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},...options,signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Failure(path.startsWith('/auth')?'invalid_sales_jwt':'sales_read_unavailable',path.startsWith('/auth')?401:503);return r.json()}
async function transaction(fn:any){const c=await pool.connect();try{await c.query('begin');await c.query("select pg_advisory_xact_lock(712601)");const result=await fn(c);await c.query('commit');return result}catch(e){await c.query('rollback');throw e}finally{c.release()}}
async function resolve(c:any,endpoint:string|null=null){const {rows}=await c.query(`select b.endpoint,b.enabled,b.enabled_at,b.dry_run_at,p.enabled as push_enabled,p.subscription,p.badge_enabled,p.badge_count from public.sales_push_bindings b join public.push_subscriptions p on p.endpoint=b.endpoint where b.enabled and b.sales_user_id=$1 and b.sales_agent_id=$2 and b.agent_name=$3 and p.enabled for share of b,p`,[PILOT.user,PILOT.agent,PILOT.name]);if(rows.length!==1)throw new Failure('recipient_count_'+rows.length,409);if(endpoint&&rows[0].endpoint!==endpoint)throw new Failure('different_pilot_device',409);if(rows[0].subscription?.endpoint!==rows[0].endpoint)throw new Failure('subscription_endpoint_mismatch',409);return rows[0]}
async function mask(e:string){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(e));return new URL(e).host+' / '+Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,12)}
const dependencies={origins,log:(code:string)=>console.warn('[sales-push]',code),verify:async(token:string)=>sales(token,'/auth/v1/user'),identity:async(token:string,id:string)=>{const links=await sales(token,'/rest/v1/agent_user_links?select=user_id,agent_id,active&active=eq.true&user_id=eq.'+encodeURIComponent(id));if(links.length!==1)return null;const a=await sales(token,'/rest/v1/agents?select=id,name,active&id=eq.'+encodeURIComponent(links[0].agent_id));return a.length===1?{user:id,agent:a[0].id,name:a[0].name,active:links[0].active,agentActive:a[0].active}:null},admin:async(token:string)=>(await sales(token,'/rest/v1/rpc/is_admin',{method:'POST',body:'{}'}))===true,submission:async(token:string,id:string)=>(await sales(token,'/rest/v1/sales_submissions?select=id,agent_id,submitter_user_id,status,revision&id=eq.'+encodeURIComponent(id)))[0],audits:async(token:string,id:string)=>sales(token,'/rest/v1/sales_submission_reviews?select=action,revision,acted_at&submission_id=eq.'+encodeURIComponent(id)),
bind:async(e:string)=>transaction(async(c:any)=>{const old=await c.query('select endpoint from public.sales_push_bindings where enabled for update');if(old.rows.some((r:any)=>r.endpoint!==e))throw new Failure('pilot_device_already_registered',409);const {rows}=await c.query('select endpoint from public.push_subscriptions where endpoint=$1 and enabled for share',[e]);if(rows.length!==1)throw new Failure('push_subscription_required',409);await c.query(`insert into public.sales_push_bindings(endpoint,sales_user_id,sales_agent_id,agent_name) values($1,$2,$3,$4) on conflict(endpoint) do update set enabled=true,updated_at=now(),enabled_at=case when sales_push_bindings.enabled then sales_push_bindings.enabled_at else now() end,dry_run_at=case when sales_push_bindings.enabled then sales_push_bindings.dry_run_at else null end`,[e,PILOT.user,PILOT.agent,PILOT.name]);return{enabled:true,agent:PILOT.name,endpoint:await mask(e)}}),
status:async(e:string)=>{const r=await pool.query('select enabled from public.sales_push_bindings where endpoint=$1 and sales_user_id=$2',[e,PILOT.user]);return{enabled:r.rows[0]?.enabled===true}},disable:async(e:string)=>transaction(async(c:any)=>{await c.query('update public.sales_push_bindings set enabled=false,updated_at=now(),dry_run_at=null where endpoint=$1 and sales_user_id=$2',[e,PILOT.user]);return{enabled:false}}),
dryRun:async(e:string|null,event:any=null)=>transaction(async(c:any)=>{const r=await resolve(c,e);if(!event)await c.query('update public.sales_push_bindings set dry_run_at=now() where endpoint=$1',[r.endpoint]);return{agent:PILOT.name,recipient_count:1,push_enabled:r.push_enabled,binding_enabled:r.enabled,endpoint:await mask(r.endpoint),event_type:event?.event||'test',revision:event?.revision??0,event_eligible:true,live_delivery_eligible:!event||Date.parse(event.actedAt)>=Date.parse(r.enabled_at)}}),
deliver:async(event:any)=>{const claimed=await transaction(async(c:any)=>{const r=await resolve(c,event.endpoint);if(event.dryRequired&&!r.dry_run_at)throw new Failure('dry_run_required',409);if(event.actedAt&&Date.parse(event.actedAt)<Date.parse(r.enabled_at))throw new Failure('historical_event_blocked',409);const claim=await c.query(`insert into public.sales_notification_deliveries(submission_id,event_type,revision,recipient_sales_user_id,endpoint,status) values($1,$2,$3,$4,$5,'processing') on conflict do nothing returning id`,[event.submission,event.event,event.revision,PILOT.user,r.endpoint]);return{row:r,id:claim.rows[0]?.id}});if(!claimed.id)return{duplicate:true,sent:0,failed:0};
let accepted=false;try{return await transaction(async(c:any)=>{const r=await resolve(c,claimed.row.endpoint);if(event.dryRequired&&!r.dry_run_at)throw new Failure('dry_run_required',409);const settings=await c.query('select vapid_public_key,vapid_private_key from public.push_settings where id=1');if(settings.rows.length!==1)throw new Failure('push_settings_unavailable',503);webpush.setVapidDetails(origins[0],settings.rows[0].vapid_public_key,settings.rows[0].vapid_private_key);const [title,body]=CONTENT[event.event as keyof typeof CONTENT];const payload=JSON.stringify({web_push:8030,mutable:false,badge_enabled:r.badge_enabled!==false,...(r.badge_enabled!==false?{app_badge:String(r.badge_count||0)}:{}),notification:{title,body,navigate:origins[0]+'/#sales',tag:'ngc-sales-'+claimed.id,silent:false,...(r.badge_enabled!==false?{app_badge:String(r.badge_count||0)}:{})}});await webpush.sendNotification(r.subscription,payload,{TTL:86400,urgency:'normal',timeout:10000});accepted=true;await c.query("update public.sales_notification_deliveries set status='sent',sent_at=now() where id=$1",[claimed.id]);return{sent:1,failed:0,recipient_count:1,endpoint:await mask(r.endpoint)}})}catch{await pool.query("update public.sales_notification_deliveries set status=$2,error_code=$3 where id=$1 and status='processing'",[claimed.id,accepted?'unknown':'failed',accepted?'delivery_receipt_uncertain':'targeted_push_failed']);throw new Failure(accepted?'delivery_receipt_uncertain':'targeted_push_failed',503)}}
};
Deno.serve(createHandler(dependencies));
