import {Pool} from 'npm:pg@8.16.3';
import webpush from 'npm:web-push@3.6.7';
import {createHandler,Failure,PILOT,CONTENT} from './core.mjs';
import {createRoutingStore,mask} from './routing-store.mjs';
const SALES='https://ejhwbovqtcujjwvjniyt.supabase.co';
const SALES_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqaHdib3ZxdGN1amp3dmpuaXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1MDYyMjksImV4cCI6MjA4MTA4MjIyOX0.GBf7fuVOE9m3jCcPGSaMWrfWyaRG6Bo3p5kb8wE6ZFo";
const pool=new Pool({connectionString:Deno.env.get('SUPABASE_DB_URL'),max:3,connectionTimeoutMillis:10000,idleTimeoutMillis:30000});
const origins=['https://ngc-super-app.vercel.app','https://ngc-sales-tracker.vercel.app'];
async function sales(token:string,path:string,options:Record<string,unknown>={}){const r=await fetch(SALES+path,{headers:{apikey:SALES_KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},...options,signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Failure(path.startsWith('/auth')?'invalid_sales_jwt':'sales_read_unavailable',path.startsWith('/auth')?401:503);return r.json()}
async function transaction(fn:any){const c=await pool.connect();try{await c.query('begin');await c.query("select pg_advisory_xact_lock(712601)");const result=await fn(c);await c.query('commit');return result}catch(e){await c.query('rollback');throw e}finally{c.release()}}
const dependencies:any={origins,log:(code:string)=>console.warn('[sales-push]',code),verify:async(token:string)=>sales(token,'/auth/v1/user'),identity:async(token:string,id:string)=>{const links=await sales(token,'/rest/v1/agent_user_links?select=user_id,agent_id,active&active=eq.true&user_id=eq.'+encodeURIComponent(id));if(links.length!==1)return null;const a=await sales(token,'/rest/v1/agents?select=id,name,active&id=eq.'+encodeURIComponent(links[0].agent_id));return a.length===1?{user:id,agent:a[0].id,name:a[0].name,active:links[0].active,agentActive:a[0].active}:null},admin:async(token:string)=>(await sales(token,'/rest/v1/rpc/is_admin',{method:'POST',body:'{}'}))===true,submission:async(token:string,id:string)=>(await sales(token,'/rest/v1/sales_submissions?select=id,agent_id,submitter_user_id,status,revision&id=eq.'+encodeURIComponent(id)))[0],audits:async(token:string,id:string)=>sales(token,'/rest/v1/sales_submission_reviews?select=action,revision,acted_at&submission_id=eq.'+encodeURIComponent(id)),
bind:async(e:string)=>transaction(async(c:any)=>{const old=await c.query('select endpoint from public.sales_push_bindings where enabled for update');if(old.rows.some((r:any)=>r.endpoint!==e))throw new Failure('pilot_device_already_registered',409);const {rows}=await c.query('select endpoint from public.push_subscriptions where endpoint=$1 and enabled for share',[e]);if(rows.length!==1)throw new Failure('push_subscription_required',409);await c.query(`insert into public.sales_push_bindings(endpoint,sales_user_id,sales_agent_id,agent_name) values($1,$2,$3,$4) on conflict(endpoint) do update set enabled=true,updated_at=now(),enabled_at=case when sales_push_bindings.enabled then sales_push_bindings.enabled_at else now() end,dry_run_at=case when sales_push_bindings.enabled then sales_push_bindings.dry_run_at else null end`,[e,PILOT.user,PILOT.agent,PILOT.name]);return{enabled:true,agent:PILOT.name,endpoint:await mask(e)}}),
status:async(e:string)=>{const r=await pool.query('select enabled from public.sales_push_bindings where endpoint=$1 and sales_user_id=$2',[e,PILOT.user]);return{enabled:r.rows[0]?.enabled===true}},disable:async(e:string)=>transaction(async(c:any)=>{await c.query('update public.sales_push_bindings set enabled=false,updated_at=now(),dry_run_at=null where endpoint=$1 and sales_user_id=$2',[e,PILOT.user]);return{enabled:false}}),
};
dependencies.latestSubmission=async(token:string)=>(await sales(token,'/rest/v1/sales_submissions?select=id,agent_id,submitter_user_id,status,revision&status=eq.approved&order=updated_at.desc&limit=1'))[0];
const routing=createRoutingStore({transaction,query:(sql:any,args:any)=>pool.query(sql,args),settings:async()=>{const r=await pool.query('select vapid_public_key,vapid_private_key from public.push_settings where id=1');if(r.rows.length!==1)throw new Failure('push_settings_unavailable',503);return r.rows[0]},trackerOrigin:origins[1],agentOrigin:origins[0],send:async(subscription:any,payload:any,cfg:any)=>{webpush.setVapidDetails(origins[0],cfg.vapid_public_key,cfg.vapid_private_key);await webpush.sendNotification(subscription,JSON.stringify(payload),{TTL:86400,urgency:'normal',timeout:10000})}});
Deno.serve(createHandler({...dependencies,...routing}));
