import {Failure,PILOT,CONTENT,ADMIN_CONTENT,recipientRole} from './core.mjs';
export async function mask(e){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(e));return new URL(e).host+' / '+Array.from(new Uint8Array(h)).map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,12)}
export function createRoutingStore({transaction,query,send,settings,trackerOrigin,agentOrigin}){
 async function resolve(c,event,endpoint=null){const admin=event.role==='tracker_admin';const table=admin?'tracker_push_bindings':'sales_push_bindings';const identity=admin?'b.tracker_user_id':'b.sales_user_id';const where=admin?'':` and b.sales_user_id=$1 and b.sales_agent_id=$2 and b.agent_name=$3`;
  const {rows}=await c.query(`select b.endpoint,b.enabled,b.enabled_at,b.dry_run_at,${identity} as recipient_user,p.enabled as push_enabled,p.subscription,p.badge_enabled,p.badge_count from public.${table} b join public.push_subscriptions p on p.endpoint=b.endpoint where b.enabled and p.enabled${where} for share of b,p`,admin?[]:[PILOT.user,PILOT.agent,PILOT.name]);
  if(rows.length!==1)throw new Failure('recipient_count_'+rows.length,409);const r=rows[0];if(endpoint&&r.endpoint!==endpoint)throw new Failure('different_registered_device',409);if(admin&&event.recipientUser&&event.event==='admin_test'&&r.recipient_user!==event.recipientUser)throw new Failure('not_binding_owner',403);if(r.subscription?.endpoint!==r.endpoint)throw new Failure('subscription_endpoint_mismatch',409);return r;
 }
 return {
  adminPublicKey:async()=>({publicKey:(await settings()).vapid_public_key}),
  adminBind:async(sub,user)=>transaction(async c=>{const old=await c.query('select endpoint,tracker_user_id from public.tracker_push_bindings where enabled for update');if(old.rows.some(r=>r.endpoint!==sub.endpoint||r.tracker_user_id!==user))throw new Failure('admin_device_already_registered',409);const agent=await c.query('select endpoint from public.sales_push_bindings where endpoint=$1',[sub.endpoint]);if(agent.rows.length)throw new Failure('agent_endpoint_not_admin',409);const prior=await c.query('select tracker_user_id from public.tracker_push_bindings where endpoint=$1',[sub.endpoint]);if(prior.rows.length&&prior.rows[0].tracker_user_id!==user)throw new Failure('not_binding_owner',403);
   await c.query(`insert into public.push_subscriptions(endpoint,subscription,enabled,campaign_enabled,general_enabled,cutoff_enabled,commission_enabled) values($1,$2,true,false,false,false,false) on conflict(endpoint) do update set subscription=excluded.subscription,enabled=true`,[sub.endpoint,JSON.stringify(sub)]);
   await c.query(`insert into public.tracker_push_bindings(endpoint,tracker_user_id) values($1,$2) on conflict(endpoint) do update set enabled=true,updated_at=now(),enabled_at=case when tracker_push_bindings.enabled then tracker_push_bindings.enabled_at else now() end,dry_run_at=case when tracker_push_bindings.enabled then tracker_push_bindings.dry_run_at else null end`,[sub.endpoint,user]);return{enabled:true,recipient_role:'tracker_admin',endpoint:await mask(sub.endpoint)}}),
  adminStatus:async(e,user)=>{const r=await query('select enabled from public.tracker_push_bindings where endpoint=$1 and tracker_user_id=$2',[e,user]);return{enabled:r.rows[0]?.enabled===true}},
  adminDisable:async(e,user)=>transaction(async c=>{await c.query('update public.tracker_push_bindings set enabled=false,dry_run_at=null,updated_at=now() where endpoint=$1 and tracker_user_id=$2',[e,user]);return{enabled:false}}),
  dryRun:async(e,event=null)=>transaction(async c=>{event=event||{event:'test',role:'sales_agent'};if(!['test','admin_test'].includes(event.event))event={...event,role:recipientRole(event.event)};const r=await resolve(c,event,e);if(['test','admin_test'].includes(event.event))await c.query(`update public.${event.role==='tracker_admin'?'tracker_push_bindings':'sales_push_bindings'} set dry_run_at=now() where endpoint=$1`,[r.endpoint]);const duplicate=event.submission?await c.query('select id from public.sales_notification_deliveries where submission_id=$1 and event_type=$2 and revision=$3',[event.submission,event.event,event.revision]):{rows:[]};return{recipient_role:event.role,recipient_count:1,tracker_admin_recipient_count:event.role==='tracker_admin'?1:0,sales_agent_recipient_count:event.role==='sales_agent'?1:0,agent:event.role==='sales_agent'?PILOT.name:undefined,endpoint:await mask(r.endpoint),event_type:event.event,revision:event.revision||0,event_eligible:true,historical_claim_exists:duplicate.rows.length>0,live_delivery_eligible:!duplicate.rows.length&&(!event.actedAt||Date.parse(event.actedAt)>=Date.parse(r.enabled_at))}}),
  deliver:async event=>{event={...event,role:event.event==='admin_test'?'tracker_admin':event.event==='test'?'sales_agent':recipientRole(event.event)};const type=event.event==='admin_test'?'test':event.event;const claim=await transaction(async c=>{const r=await resolve(c,event,event.endpoint);if(event.dryRequired&&!r.dry_run_at)throw new Failure('dry_run_required',409);if(event.actedAt&&Date.parse(event.actedAt)<Date.parse(r.enabled_at))throw new Failure('historical_event_blocked',409);const out=await c.query(`insert into public.sales_notification_deliveries(submission_id,event_type,revision,recipient_sales_user_id,recipient_role,recipient_tracker_user_id,endpoint,status) values($1,$2,$3,$4,$5,$6,$7,'processing') on conflict do nothing returning id`,[event.submission,type,event.revision,PILOT.user,event.role,event.role==='tracker_admin'?r.recipient_user:null,r.endpoint]);return{id:out.rows[0]?.id,endpoint:r.endpoint,recipient:r.recipient_user}});if(!claim.id)return{duplicate:true,sent:0,failed:0,recipient_role:event.role};let accepted=false;
   try{return await transaction(async c=>{const r=await resolve(c,event,claim.endpoint);if(r.recipient_user!==claim.recipient)throw new Failure('recipient_changed',409);if(event.dryRequired&&!r.dry_run_at)throw new Failure('dry_run_required',409);const cfg=await settings();const [title,body]=event.event==='admin_test'?ADMIN_CONTENT:CONTENT[event.event];const navigate=event.role==='tracker_admin'?trackerOrigin+'/#review':agentOrigin+'/#sales';await send(r.subscription,{web_push:8030,mutable:false,badge_enabled:r.badge_enabled!==false,...(r.badge_enabled!==false?{app_badge:String(r.badge_count||0)}:{}),notification:{title,body,navigate,tag:'ngc-sales-'+claim.id,silent:false,...(r.badge_enabled!==false?{app_badge:String(r.badge_count||0)}:{})}},cfg);accepted=true;await c.query("update public.sales_notification_deliveries set status='sent',sent_at=now() where id=$1",[claim.id]);return{sent:1,failed:0,recipient_count:1,recipient_role:event.role,tracker_admin_recipient_count:event.role==='tracker_admin'?1:0,sales_agent_recipient_count:event.role==='sales_agent'?1:0,endpoint:await mask(r.endpoint)}})}catch{await query("update public.sales_notification_deliveries set status=$2,error_code=$3 where id=$1 and status='processing'",[claim.id,accepted?'unknown':'failed',accepted?'delivery_receipt_uncertain':'targeted_push_failed']);throw new Failure(accepted?'delivery_receipt_uncertain':'targeted_push_failed',503)}
  }
 };
}
