import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import path from 'node:path';import crypto from 'node:crypto';
const app=path.resolve(import.meta.dirname,'..'),module=fs.readFileSync(path.join(app,'work/sales/module.html'),'utf8');let passed=0;const test=(name,fn)=>{fn();passed++;console.log('PASS '+name)};
const handlers={};const store=new Map(),elements={root:{innerHTML:'',addEventListener(name,fn){handlers[name]=fn},querySelector(){return null}},message:{}};const client={auth:{onAuthStateChange(){}},rpc:async()=>({error:{message:'Network unavailable'}})};
const ctx=vm.createContext({supabase:{createClient:()=>client},SALES_URL:'http://127.0.0.1',SALES_KEY:'test',document:{getElementById:id=>elements[id]},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},navigator:{onLine:true},window:{addEventListener(){}},crypto,console,Date,URLSearchParams});
const script=module.split('<script>/* SALES_VENDOR */</script><script>')[1].split('</script>')[0].split('(async()=>{try{const h=parent.location.hash')[0];vm.runInContext(script,ctx);const run=s=>vm.runInContext(s,ctx);
const valid={record_date:'2026-10-03',client_name:'Test reference',transaction_type:'N. Business',remark:'',total_investment:'10000',items:[{product_name:'Equity',product_type:'Cash EQ',gross_investment:'10000',sales_charge:'3',ps_rate:'1.9'}],attempt:null};const set=v=>run('draft='+JSON.stringify(v));const invalid=(name,edit)=>test(name,()=>{const v=structuredClone(valid);edit(v);set(v);assert.ok(run('validation()'))});
test('valid single fund',()=>{set(valid);assert.equal(run('validation()'),'')});test('exact Tracker net and commission operation order',()=>{const v=run('totals()');assert.equal(v.net,10000/(1+(3/100)*(1+.08)));assert.equal(v.commission,v.net*(1.9/100))});
test('multi fund total and independent unrounded calculations',()=>{const v=structuredClone(valid);v.total_investment='15000';v.items.push({...v.items[0],product_name:'MM',product_type:'Cash MM',gross_investment:'5000',sales_charge:'0',ps_rate:'0'});set(v);assert.equal(run('validation()'),'');assert.equal(run('totals().commission'),10000/(1+(3/100)*1.08)*(.019))});
invalid('allocation mismatch',v=>v.total_investment='9999');invalid('negative gross',v=>v.items[0].gross_investment='-1');invalid('fractional cents',v=>v.total_investment='10000.001');invalid('blank gross',v=>v.items[0].gross_investment='');invalid('nonfinite amount',v=>v.total_investment='Infinity');invalid('SC over 6.5 percent',v=>v.items[0].sales_charge='6.6');invalid('negative SC',v=>v.items[0].sales_charge='-1');invalid('PS over 100 percent',v=>v.items[0].ps_rate='101');invalid('invalid product type',v=>v.items[0].product_type='made up');invalid('invalid transaction type',v=>v.transaction_type='made up');invalid('missing client reference',v=>v.client_name=' ');invalid('oversized reference',v=>v.client_name='x'.repeat(201));invalid('oversized remark',v=>v.remark='x'.repeat(2001));invalid('invalid calendar date',v=>v.record_date='2026-02-30');invalid('date before supported range',v=>v.record_date='1899-12-31');invalid('zero items',v=>v.items=[]);invalid('over 100 items',v=>v.items=Array.from({length:101},()=>v.items[0]));
test('draft scoped to account',()=>{set(valid);run("user={id:'a'};save();user={id:'b'}");assert.equal(run('loadDraft()'),null);run("user={id:'a'}");assert.equal(run('loadDraft().client_name'),valid.client_name)});test('expired drafts removed',()=>{store.set('ngc-sales-draft-v1:a',JSON.stringify({saved_at:Date.now()-8*86400000,draft:valid}));assert.equal(run('loadDraft()'),null);assert.equal(store.has('ngc-sales-draft-v1:a'),false)});test('HTML escaping client controlled values',()=>assert.equal(run("esc('<img onerror=alert(1)>')"),'&lt;img onerror=alert(1)&gt;'));

for(const [type,rate] of [['EPF','2.2'],['PRS','0.9']])test(type+' product change updates only selected fund PS default',()=>{set({...valid,items:[{...valid.items[0]},{...valid.items[0]}]});run("view='form';user={id:'rate-test'};updateSummary=()=>{}");elements['rates-1']={innerHTML:''};handlers.change({target:{dataset:{item:'1',field:'product_type'},value:type}});assert.equal(run('draft.items[1].ps_rate'),rate);assert.ok(elements['rates-1'].innerHTML.includes('value="'+rate+'"'));assert.ok(elements['rates-1'].innerHTML.includes('readonly'));assert.equal(run('draft.items[0].ps_rate'),valid.items[0].ps_rate);assert.equal(run('loadDraft().items[1].ps_rate'),rate)});
test('Tracker fixed rate matrix and Cash EQ tiers',()=>{for(const [type,sc,ps] of [['EPF',3,2.2],['PRS',1.5,.9],['Cash MM',0,0]]){assert.equal(run('defaultSC('+JSON.stringify(type)+')'),sc);assert.equal(run('defaultPS('+JSON.stringify(type)+','+sc+')'),ps);assert.equal(run('fixedRates('+JSON.stringify(type)+')'),true)}assert.equal(run("defaultPS('Cash EQ',5.5)"),3);assert.equal(run("defaultPS('Cash EQ',3)"),1.9);assert.equal(run("fixedRates('Cash EQ')"),false)});
run('renderForm=()=>{};refresh=async()=>{};detail=async()=>{}');set(valid);run("user={id:'a'}");const requests=[];client.rpc=async(name,payload)=>{requests.push(structuredClone(payload));return {error:{message:'Network unavailable'}}};await run('send()');await run('send()');test('lost responses retain one immutable request ID',()=>{assert.equal(requests.length,2);assert.equal(requests[0].p_client_request_id,requests[1].p_client_request_id);assert.deepEqual(requests[0],requests[1]);assert.ok(run('loadDraft().attempt'));assert.equal(run('success'),'')});
run('busy=true');await run('send()');test('inflight double tap ignored',()=>assert.equal(requests.length,2));run('busy=false');ctx.navigator.onLine=false;await run('send()');test('offline makes no RPC and preserves draft',()=>{assert.equal(requests.length,2);assert.ok(run('loadDraft()'))});ctx.navigator.onLine=true;client.rpc=async()=>({data:{submission_id:'local'}});await run('send()');test('only successful RPC clears draft',()=>{assert.equal(run('draft'),null);assert.equal(store.has('ngc-sales-draft-v1:a'),false)});
const baseline=fs.readFileSync(path.join(app,'work/sales/baseline-super-app.html'),'utf8'),current=fs.readFileSync(path.join(app,'outputs/index.html'),'utf8');test('generated HTML aliases match',()=>assert.equal(current,fs.readFileSync(path.join(app,'outputs/ngc_super_app.html'),'utf8')));test('original module payloads preserved byte for byte',()=>{for(const m of baseline.matchAll(/html:\s*["']([A-Za-z0-9+/=]{100,})["']/g))assert.ok(current.includes(m[0]))});test('original shell preserved after reversing five additions',()=>{let reversed=current.replace(/\n      sales: \{name:"Sales"[^\n]+\},/,'').replace('\n      sales:document.getElementById("salesFrame"),','').replace(/\n        <button class="app-card" type="button" data-open="sales"[^\n]+<\/button>/,'').replace('<iframe id="salesFrame" data-app="sales" title="Sales" sandbox="allow-scripts allow-same-origin allow-forms"></iframe>\n      ','').replace('const initial = location.hash.includes("access_token=") ? "sales" : location.hash.slice(1);','const initial = location.hash.slice(1);');assert.equal(reversed.replace('<h2>Commission</h2>','<h2>Commission Calculator</h2>'),baseline)});test('all embedded scripts parse',()=>{for(const m of current.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/gi))if(!/src=|application\/json/.test(m[1]))new Function(m[2]);new Function(script)});test('all protected assets including service worker manifest and admin pages unchanged',()=>{const hashes=JSON.parse(fs.readFileSync(path.join(app,'work/sales/protected-assets.json')));for(const [file,hash] of Object.entries(hashes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(app,file))).digest('hex'),hash,file)});test('Sales uses only Tracker public anon key',()=>{const c=JSON.parse(fs.readFileSync(path.join(app,'work/sales/config.json')));assert.equal(JSON.parse(Buffer.from(c.public_key.split('.')[1],'base64url')).role,'anon');assert.ok(module.includes('ngc-sales-auth-v1'));assert.ok(current.includes('salesFrame'))});test('srcdoc email redirect uses the parent Super App origin',()=>{assert.ok(module.includes("emailRedirectTo:parent.location.origin+'/#sales'"));assert.ok(!module.includes("emailRedirectTo:location.origin"))});console.log(`${passed} tests passed`);
